version: 2
jobs:
  build:
    docker:
      - image: gradle:jdk8-alpine
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Print environment
          command: uname -a
      # - run:
      #     name: Failing step
      #     command: "false"
      - run:
          name: Succeeding step
          command: "true"
      - run:
          name: Gradle build
          command: gradle build


